services:
  - type: worker
    name: bids
    env: docker
    dockerCommand: python -m tasks.track_bids
    branch: main
    envVars:
      - fromGroup: settings
  - type: worker
    name: sales
    env: docker
    dockerCommand: python -m tasks.track_phunkbot_sales
    branch: main
    envVars:
      - fromGroup: settings
  - type: worker
    name: nftx
    env: docker
    dockerCommand: python -m tasks.track_nftx_purchases
    branch: main
    envVars:
      - fromGroup: settings
  - type: worker
    name: schedule
    env: docker
    dockerCommand: python -m tasks.schedule_tasks --stats --sniper
    branch: main
    envVars:
      - fromGroup: settings




envVarGroups:
  - name: settings
    envVars:
      - key: MAINNET_HTTP_PROVIDER_URL
        sync: false
      - key: MAINNET_WS_PROVIDER_URL
        sync: false
      - key: ETHERSCAN_API_KEY
        sync: false
      - key: TWITTER_ACCESS_SECRET
        sync: false
      - key: TWITTER_ACCESS_TOKEN
        sync: false
      - key: TWITTER_API_KEY
        sync: false
      - key: TWITTER_API_SECRET
        sync: false
      - key: TWITTER_BEARER_TOKEN
        sync: false
      - key: MONGO_CONN_STRING
        sync: false
      - key: COVALENT_API_KEY
        sync: false
      - key: MORALIS_API_KEY
        sync: false
      - key: TESTING
        sync: false
